<?php

/**
 * Dianne Abbott Facts as a service
 */


namespace AbbottFact;

class Fact
{
    /**
     * Generate a fact
     * @return string
     */
    function __construct()
    {
        $words = ["1% of all", "2% of all", "3% of all", "4% of all", "5% of all", "6% of all", "7% of all", "8% of all", "9% of all", "10% of all", "11% of all", "12% of all", "13% of all", "14% of all", "15% of all", "16% of all", "17% of all", "18% of all", "19% of all", "20% of all", "21% of all", "22% of all", "23% of all", "24% of all", "25% of all", "26% of all", "27% of all", "28% of all", "29% of all", "30% of all", "31% of all", "32% of all", "33% of all", "34% of all", "35% of all", "36% of all", "37% of all", "38% of all", "39% of all", "40% of all", "41% of all", "42% of all", "43% of all", "44% of all", "45% of all", "46% of all", "47% of all", "48% of all", "49% of all", "50% of all", "51% of all", "52% of all", "53% of all", "54% of all", "55% of all", "56% of all", "57% of all", "58% of all", "59% of all", "60% of all", "61% of all", "62% of all", "63% of all", "64% of all", "65% of all", "66% of all", "67% of all", "68% of all", "69% of all", "70% of all", "71% of all", "72% of all", "73% of all", "74% of all", "75% of all", "76% of all", "77% of all", "78% of all", "79% of all", "80% of all", "81% of all", "82% of all", "83% of all", "84% of all", "85% of all", "86% of all", "87% of all", "88% of all", "89% of all", "90% of all", "91% of all", "92% of all", "93% of all", "94% of all", "95% of all", "96% of all", "97% of all", "98% of all", "99% of all", "Very Few", "Most", "Almost All", "Most Small", "Most Large", "Most Medium-Sized", "Most Hairy", "Most Ceritfied", "Most Left Handed", "A Significant Number Of", "Several", "Hundreds of", "Many Wild Packs Of", "Many Psychotic", "A Surprising Number Of", "Many Unemployed", "Most Drug Taking", "Many Drunken", "Many Hallucinating", "ManyOverweight", "Many Socially Inept"];
        $words1 = ["Frogs", "Hamsters", "Housewives", "Hobos", "Fat Kids", "Teachers", "Magicians", "Dinner Ladys", "Civil Servants", "Families", "Historians", "Football Mascots", "Musicians", "Librarians", "Monkeys", "Chimpanzees", "Ex-Rap Stars", "Eighties Pop Stars", "Rock Stars", "Antelopes", "Norweigen Sailors", "Sharks", "Ex-Postmen", "Village Idiots", "Bikers", "Priests", "Ex-Priests", "Ex-Teachers", "Sales Reps", "Viking Warriors", "Earwigs", "Opera Singers", "Dwarves", "Women", "Men", "Soapstars", "Students", "Elephants", "Humanzees", "Clowns", "Farmers", "Failed Actors", "Muppets", "Firefighters", "Barbie Dolls", "Dogs", "Orangutangs", "Cows", "Sheep", "French Exchange Students", "Rabbits", "Men Called Dave", "Women Called Mrs Dave", "Monkey Butlers", "Butlers", "Monkey Miners", "Plague Victims", "Chimpage Fans", "Conservatives", "Daily Mail Readers", "Marathon Runners", "World Leaders", "Musketeers", "World Leaders", "Golfers", "Footballers", "One Armed Banditos", "Toilet paper Manufacturers", "Mud Wrestlers", "Cynics", "Historical Re-enactors", "Sports Commentators", "Tom Hanks Look-a-likes", "Pilots", "Naked Ramblers", "Fire Eaters", "School Bullies", "Ugly People", "Alien Abductees", "Mime Artists", "Old People"];
        $words2 = ["Eat", "Hibernate", "Are Run Over", "Breed", "Shave Off Their Bodyhair", "Play Indoor Tennis", "Fight Polar Bears", "Sweep Roads", "Climb Trees", "Used to Be Bullied", "Launch Space Vehicles", "Hold Parties", "Vote For Labour", "Are Struck By Lightning", "Speed Date", "Smoke Dried Earwigs", "Eat Their Own Earwax", "Re-enact Episodes of Eastenders", "Mend Fridges", "Befriend Fridges", "Produce Small Budget Horror Films", "Make Love Not War", "Make War Not Love", "Golf", "Cook", "Mud-Wrestle", "Cake Decorate", "Draw With Crayons", "Go On Nocturnal Safaris", "Alligator Hunt", "Play Scrabble Naked", "Fly Kites", "Limp", "Shoot Pigeons", "Headbutt People", "Lick Old People", "Write Spam E-mails", "Perform Altruistic Acts", "Perform the Can Can", "Liberate Dictatorships", "Walk Into Doorways", "Talk to God", "Worship  Different gods", "Become gods", "Lie Down", "Speak Their Mind", "Run Marathons", "Trip Up", "Trip Up Old People", "Pretend to be the Pope", "Catch Fire", "Solve Global Warming", "Cut Their Nails", "Become Single Parents", "Comb Their Hair", "Shoplift", "Are Trapped In Lifts", "Install Central Heating", "Catch Buses", "Catch Diseases", "Grow Potatoes", "Clone Small Animals", "Hold Woodland Creatures Hostage", "Drive a Tractor", "Moonlight as Taxi Drivers", "Cry", "Shout For Help", "Hop Backwards", "Pretend to be Hobbits", "Watch Star Trek", "Brush Their Teeth", "Shave Their Legs", "Decapitate Rabbits", "Paint Self-Portraits", "Stalk People", "Attend Pointless Conferences", "Convert to Catholicism", "Vomit", "Collect Stamps", "Defuse Bombs", "Fry Sausages", "Eat People", "Rob Banks", "Drive Cars", "Collect Magic Herbs", "Gatecrash Weddings", "Talk to Priests", "Talk to a Monkey", "Are Arsonists", "Pretend to be Pixies"];
        $words3 = ["At Any One Time", "But Keep It A Secret", "In the Workplace", "On a daily basis", "On a Part Time basis", "During Their Lunch Break", "In the Dark", "Every  Minutes", "In the Arctic Circle", "During the Hours of Darkness", "During Summer", "During Autumn", "During Winter", "In the Springtime", "At School", "On A Monday", "On A Tuesday", "On a Wednesday", "On a Thursday", "On a Friday", "On a Saturday", "On a Sunday", "In the Month Of April", "In the Month of May", "In a Bus Queue", "In a Bus Shelter", "In and Around a Library", "In a Park", "When People Aren't Looking", "In Switzerland", "When the Moon is Full", "When the Sun is in the North", "In an Igloo", "Via the Medium of Dance", "Whilst Wearing Fur", "Professionally", "For Fun", "In the Bath", "Whilst Whistling", "Whilst Playing the Trumpet", "When the Wind Blows a Gale", "During Lambing Season", "Accidentally", "Out of Fear", "For No Apparent Reason", "Unintenionally", "Deliberately", "As Often as they Can", "In Urban Areas", "Twice Every Minute"];

        return $words[array_rand($words)] . " " . $words1[array_rand($words1)] . " " . $words2[array_rand($words2)] . " " . $words3[array_rand($words3)] . ".";
    }

}